#!/bin/bash

./gradlew build
# scp -P 1337 lib/build/libs/FireCat.jar mira@solarsystem.coffee:/home/risingphoenix/phoenix/plugins/
scp lib/build/libs/FireCat.jar mira@tea.sparklet.org:~/surv/plugins/
